import { Project } from '../../types';

export const PROJECTS: Project[] = [
    {
        id: 'arch',
        num: '01',
        title: 'React migration',
        section: 'Braze',
        blurb: 'Completed my team’s migration of the Braze dashboard to React — rebuilding the navigation and converting hooks on core components along the way.',
        tags: ['TypeScript', 'React'],
    },
    {
        id: 'target',
        num: '02',
        title: 'Calculated filters',
        section: 'Braze',
        blurb: 'Built the API and a lot of the frontend for this feature. Additionally, built the end-to-end test infrastructure for Braze’s calculated filters feature: created a S3 bucket that wired into a local Dockerized container environment that a ClickHouse instance dumps into, wired up to run Cypress tests against the real data path.',
        tags: ['Cypress', 'ClickHouse', 'Docker', 'S3', 'React', 'Rails'],
        link: 'https://www.braze.com/docs/user_guide/audience/segments/calculated_filters',
    },
    {
        id: 'moon',
        num: '03',
        title: 'Suppression lists',
        section: 'Braze',
        blurb: 'Developed Suppression Lists for Braze — building the core segmentation backend feature in Ruby and the entire frontend in TypeScript/React.',
        tags: ['Ruby', 'TypeScript', 'React'],
        link: 'https://www.braze.com/docs/user_guide/audience/suppression_lists',
    },
    {
        id: 'squares',
        num: '04',
        title: 'This portfolio',
        section: 'Personal',
        blurb: 'Originally built from scratch in 2023, revamped using Claude (which captured my design vision better than I could). Originally used Create React App to build and test locally, and upgraded to Vite. Final design and code review by me, of course. Hosted on Netlify.',
        tags: ['TypeScript', 'React', 'Vite', 'Claude', 'CSS'],
        link: 'https://github.com/shreyaresh/portfolio',
    },
    {
        id: 'stripes',
        num: '05',
        title: 'NYRR volunteering bot',
        section: 'Personal',
        blurb: 'Chasing a 9+1 NYC Marathon entry without refreshing the NYRR site every day: a Playwright scraper that clicks through the volunteer page for open spots, shipped in Docker to Google Cloud Run on a 15-minute Cloud Scheduler loop, and pings Slack with a "Register Now" button when one appears.',
        tags: ['Python', 'Playwright', 'Docker', 'GCP'],
        link: 'https://github.com/shreyaresh/nyrr-volunteering',
    },
    {
        id: 'quarter',
        num: '06',
        title: 'Greenhouse',
        section: 'Personal',
        blurb: 'A collaborative game where you and a friend grow a garden together and nurture it over time — real-time multiplayer over Socket.io with a React drag-and-drop frontend and an Express/MongoDB backend with Google OAuth.',
        tags: ['React', 'Socket.io', 'Express', 'MongoDB'],
        link: 'https://github.com/shreyaresh/Greenhouse',
    },
    {
        id: 'ring',
        num: '07',
        title: 'Global Entry email bot',
        section: 'Personal',
        blurb: 'Global Entry appointments appear randomly and vanish in minutes, so this Python script polls the scheduler API for a chosen location and emails me the moment a slot opens up.',
        tags: ['Python', 'REST'],
        link: 'https://github.com/shreyaresh/Global-Entry',
    },
];
